--- #YAML:1.0
name:               KiokuDB-Backend-JSPON
version:            0.05
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::NFSLock:        0
    IO:                   1.2301
    IO::AtomicFile:       0
    KiokuDB:              0.10
    Moose:                0
    MooseX::Types::Path::Class:  0
    Path::Class:          0
    Test::TempDir:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
